#!/bin/bash

if [ -z "${1}" ]; then
   echo "must pass in location of LICENSE file"
   exit 1
fi


# put this in your .bash_profile
pull_request() {
  to_branch=$1
  if [ -z $to_branch ]; then
    to_branch="master"
  fi
  
  # try the upstream branch if possible, otherwise origin will do
  upstream=$(git config --get remote.upstream.url)
  origin=$(git config --get remote.origin.url)
  if [ -z $upstream ]; then
    upstream=$origin
  fi
  
  to_user=$(echo $upstream | sed -e 's/.*[\/:]\([^/]*\)\/[^/]*$/\1/')
  from_user=$(echo $origin | sed -e 's/.*[\/:]\([^/]*\)\/[^/]*$/\1/')
  repo=$(basename `git rev-parse --show-toplevel`)
  from_branch=$(git rev-parse --abbrev-ref HEAD)
  open "https://github.com/$to_user/$repo/pull/new/$to_user:$to_branch...$from_user:$from_branch"
}
 
# usage
# pull_request              # PR to master
# pull_request other_branch # PR to other_branch


for dir in /tmp/turnerlabs/*/
do
    dir=${dir%*/}
    cd $dir
    git checkout -b add-license
    cp ${1} ./LICENSE
    git add .
    git commit -s -m 'legal(LICENSE): adding Apache-2.0 License'
    git push origin add-license
    pull_request
done

